[package]
name = "xo_os"
version = "0.1.0"
authors = ["Andrey Tonkikh <xosmig@gmail.com>"]

[dependencies]
rlibc = "1.0.0"
libc = { version = "0.2.16", default-features = false }

[lib]
crate-type = ["staticlib"]

# The development profile, used for `cargo build`.
[profile.dev]
# Disable unwinding for debug build.
panic = "abort"

# The release profile, used for `cargo build --release`.
[profile.release]
# Disable unwinding for release build.
panic = "abort"
